### ISSUE TITLE
OutbidNotification tests failing

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/auction#18]
I'm getting the following error

![image](https://user-images.githubusercontent.com/692077/33549097-adac815a-d8e9-11e7-88b4-00ddb117552b.png)

which comes from this line of code:

```javascript
const lastJob = await Job.findLastByReferenceId(email)
if (!isTimeToSend(lastJob.createdAt)) {
  throw new Error(`Last notification sent less than ${hoursAgo} hours ago`)
}
```

Meaning that if there's job with the supplied `referenceId`, the service blows up. This is easily fixable by:

`if (lastJob && !isTimeToSend(lastJob.createdAt)) {`

but I'm not entirely sure if that's the intended conditional.

@abarmat

**Comment by abarmat** [comment]
Solved in https://github.com/decentraland/auction/pull/20

**Comment by nicosantangelo** [comment]
👍
